### PR TITLE
Additional Social Networks

### PR DESCRIPTION
**Pull request by englishtom**
Hi guys,

Great work on the library. I had a requirement to support some extra social networks in the project I'm working on so I've done the work to integrate them.

**Instagram** 
- Looks for usernames as the first slug in the pathname e.g. /englishtom
- Usernames are between 1 and 30 characters
- Usernames can contain alphanumeric characters and underscores

**LinkedIn** 
- Looks for usernames as the second slug in the pathname when the first slug is "in" e.g. /in/englishtom
- Usernames are between 5 and 30 characters
- Usernames can contain alphanumeric characters and hyphens

**Soundcloud**
- Looks for usernames as the first slug in the pathname e.g. /englishtom
- Usernames are between 3 and 255 characters
- Usernames can contain alphanumeric characters and underscores

**YouTube**
- Looks for usernames as the first slug in the pathname e.g. /englishtom
- Looks for usernames as the second slug in the pathname when the first slug is one of "user", "c" or "channel"
- Usernames (or ids in the case of /channel/{id}) are between 5 and 50 characters
- Usernames can contain alphanumeric characters and underscores

I couldn't find *any* definitive documentation on what format YouTube custom urls currently take. They seem to have changed a load of times as YouTube was first acquired by Google, then integrated with Google+ and then one more time since then. I've put 5 as the minimum character length as that was the shortest I've read it being mentioned as, and likewise 50 was the longest. 

Cheers,

Tom

### CODE REVIEW

**Comment by Janpot** [comment]
@englishtom Thanks for your contribution. Looks good at first sight. Will take a deeper look early next week if that's ok for you but I see no problem merging this. 

I'm glad it's useful to you. Seems like you get the idea but want to mention just in case. We don't intend for this library to do more than simple static string parsing. No url resolving or page scraping for account ids or anything. It's very lightweight but therefore also only just a best guess.

**Comment by englishtom** [comment]
Hey Jan,

No rush, next week sounds good to me- nobody likes to work on the weekend ;) 

Yeah, my use-case is just to display the appropriate social network logo and their id next to user inputted url strings (or a general web logo if none are matched). I imagine you were probably solving a similar problem when you wrote the library.

**Comment by Janpot** [comment]
@englishtom Could you just adjust the casing of `Youtube => YouTube`, `Linkedin => LinkedIn` and `Soundcloud => SoundCloud`. When I look on their sites it seems like that's the way they write their name when it's not in their logo.

**Comment by englishtom** [comment]
@Janpot Sure thing, do you want it changed in method names as well `parseYoutube => parseYouTube` or only the network name strings 

`return {
  network: 'YouTube'
  ...
}`

**Comment by Janpot** [comment]
Seems like we did it with `parseGooglePlus` as well, so I'd say to change it in the method names as well

**Comment by Janpot** [comment]
@englishtom published as `1.3.0`

**Pull request merged**
